# Generated by Django 4.1.7 on 2023-03-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Troops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('max_level', models.IntegerField(verbose_name='max level')),
                ('type', models.CharField(choices=[('elixir', 'Elixir Troops'), ('dark_elixir', 'Dark Elixir Troops')], max_length=50, verbose_name='type')),
                ('favorite_target', models.CharField(choices=[('any', 'Any'), ('defenses', 'Defenses'), ('air_defense', 'Air Defense'), ('resources', 'Resources (Damage x2)'), ('walls', 'Walls (Damage x40)'), ('heroes', 'Heroes (Damage x4)')], max_length=50, verbose_name='favorite target')),
                ('damage_type', models.CharField(choices=[('single', 'Single Target'), ('area', 'Area Splash')], max_length=50, verbose_name='damage type')),
                ('targets', models.CharField(choices=[('ground', 'Ground'), ('ground_air', 'Ground & Air')], max_length=50, verbose_name='targets')),
                ('housing_space', models.IntegerField(verbose_name='housing space')),
                ('movement_speed', models.IntegerField(verbose_name='movement speed')),
                ('training_time', models.IntegerField(verbose_name='training time')),
                ('barracks_level_required', models.IntegerField(verbose_name='barracks level required')),
            ],
        ),
    ]
