# Generated by Django 4.1.7 on 2023-03-11 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('troops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='troops',
            options={'verbose_name': 'Troop', 'verbose_name_plural': 'Troops'},
        ),
        migrations.CreateModel(
            name='TroopsUpgradeStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='level')),
                ('damage_per_second', models.IntegerField(verbose_name='damage per second')),
                ('damage_per_attack', models.IntegerField(verbose_name='damage per attack')),
                ('hitpoints', models.IntegerField(verbose_name='hitpoints')),
                ('research_cost', models.IntegerField(verbose_name='research cost')),
                ('research_time', models.IntegerField(verbose_name='research time')),
                ('laboratory_level_required', models.IntegerField(verbose_name='laboratory level required')),
                ('troops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troops.troops')),
            ],
            options={
                'verbose_name': 'Upgrade statistic',
                'verbose_name_plural': 'Upgrade statistics',
            },
        ),
    ]
