# Generated by Django 4.1.7 on 2023-03-11 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('troops', '0002_alter_troops_options_troopsupgradestatistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troopsupgradestatistic',
            name='troops',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_statistic', to='troops.troops'),
        ),
    ]
